apt_packages:
  - sudo
  - nginx
  - mariadb-server
  - mariadb-client
  - python3-pip
  - python3-mysqldb
  - unzip

php_apt_packages:
  - php
  - php-fpm
  - php-mysql
  - php-cli
  - php-common
  - php-json
  - php-opcache
  - php-readline
  - php-mbstring
  - php-xml
  - php-gd
  - php-curl
  - php-imagick 
  - php-zip
  - php-bz2 
  - php-intl
  - php-bcmath
  - php-gmp
  - libmagickcore-6.q16-6-extra

pip3_dependancies:
  - cryptography
  - python-apt