---
- name: "Install Aptitude (recommended when using apt ansible module) and update repositories cache"
  apt:
    name: aptitude
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Apt upgrade"
  apt:
    upgrade: yes

- name: "Install prerequisites"
  apt:
    name: "{{item}}"
    state: present
  loop:
    - sudo
    - nginx
    - mariadb-server
    - mariadb-client
    - python3-pip
    - python3-mysqldb

- name: "Add python 3 deps"
  pip:
    name: "{{item}}"
  loop:
    - cryptography
    - python-apt

- name: "Install PHP packages"
  apt:
    name: "{{item}}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-cli
    - php-common
    - php-json
    - php-opcache
    - php-readline
    - php-mbstring
    - php-xml
    - php-gd
    - php-curl
    - php-imagick 
    - php-zip
    - php-bz2 
    - php-intl
    - php-bcmath
    - php-gmp
