---
- name: "Install Aptitude (recommended when using apt ansible module) and update repositories cache"
  apt:
    name: aptitude
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Apt upgrade"
  apt:
    upgrade: yes

- name: "Install prerequisites"
  apt:
    name: "{{item}}"
    state: present
  loop:
    - "{{ apt_packages }}"

- name: "Add python 3 deps"
  pip:
    name: "{{item}}"
  loop:
    - "{{ pip3_dependancies }}"

- name: "Install PHP packages"
  apt:
    name: "{{item}}"
    state: present
  loop:
    - "{{ php_apt_packages }}"
