---
- name: "Install packages and prerequisites"
  ansible.builtin.include_tasks:
    file: install.yml

- name: "Configure nginx"
  ansible.builtin.include_tasks:
    file: configure_nginx.yml

- name: "Configure mariadb"
  ansible.builtin.include_tasks:
    file: configure_mariadb.yml

- name: "Secure mariadb"
  ansible.builtin.include_tasks:
    file: secure_mariadb.yml
